In [1]:
#Numpy and Pandas
#Review of main components and usage of the libraries
import numpy as np
import pandas as pd

In [3]:
#NUMPY: Tensor/array methods and random generation
tlist = [1,2,3,4,5]
arr = np.array(tlist)
type(arr)

numpy.ndarray

In [4]:
a = np.arange(0,100) #generate range of values
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
b = np.zeros((0,20)) #generate zero
b

array([], shape=(0, 20), dtype=float64)

In [9]:
b_mat = np.zeros((10,10)) #or matrix
b_mat

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
np.random.randint(0,10) #random selection

1

In [12]:
np.random.randint(0,10,(2,2)) #random matrix

array([[6, 1],
       [7, 8]])

In [14]:
np.linspace(0,1,10) #linearly spaces array

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [17]:
#Numpy operations
np.random.seed(101) #sets a seed to random generator, for reproducability in examples
arr = np.random.randint(0,100,10)
arr.max() #max, min()

95

In [18]:
arr.argmax() #index of max

0

In [19]:
arr.mean() #mean

60.799999999999997

In [20]:
arr.reshape(2,5) #reshaping tensor

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [33]:
mat = arr.reshape(2,5)
mat[0,2] #accessing index

81

In [34]:
mat > 50 #filtering on returned booleans from operation

array([[ True, False,  True,  True,  True],
       [ True,  True, False,  True, False]], dtype=bool)

In [35]:
mat[mat>50] 

array([95, 81, 70, 63, 87, 75, 77])

In [36]:
#PANDAS: grabbing stuff from csv into numpy objects / dataframes
data = pd.read_csv("data/salaries.csv") #reading comma separated files
data.head() #view head of file

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [37]:
print(data)

     Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27


In [39]:
print(data[["Salary"]]) #bracket calling columns as a list of colnames

   Salary
0   50000
1  120000
2   80000


In [40]:
data["Salary"].min() #similar access to min,max,mean etc as numpy

50000

In [42]:
data[data["Salary"] > 60000]  #conditional filtering similar to numpy

Name  Salary  Age
1   Sally  120000   45
2  Alyssa   80000   27

In [43]:
data.columns #column names

Index(['Name', 'Salary', 'Age'], dtype='object')

In [44]:
data.info() #info on dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
Name      3 non-null object
Salary    3 non-null int64
Age       3 non-null int64
dtypes: int64(2), object(1)
memory usage: 152.0+ bytes


In [46]:
#Numpy to dataframe
mat = np.arange(0,25).reshape(5,5)
df = pd.DataFrame(data=mat, columns = ["A","B","C","D","E"])
df

A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24